#!/bin/sh

# /etc/init.d/vacancy
### BEGIN INIT INFO
# Provides:		vacancy
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Starts vacancy.sh
# Description:		Runs $DAEMON which runs vacancy.py
### END INIT INFO

DIR=/home/pi/Vacancy/pi_leds
DAEMON=$DIR/vacancy.py
DAEMON_NAME=vacancy

DAEMON_OPTS=""
DAEMON_USER="pi"

PIDFILE=/var/run/$DAEMON_NAME.pid

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

do_start(){
	log_daemon_msg "Starting system $DAEMON_NAME daemon"
	start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON -- $DAEMON_OPTS
	log_end_msg $?
}

do_stop(){
	log_daemon_msg "Stopping system $DAEMON_NAME daemon"
	start-stop-daemon --stop --pidfile $PIDFILE --retry 10
	log_end_msg $?
}

case "$1" in
  start|stop)
  	do_${1}
	;;
  reload|force-reload|restart)
	do_stop
    	do_start
	;;
  status)
	status_of_proc "$DAEMON_NAME" $DAEMON && exit 0 || exit $?
	;;
  *)
	echo "Usage: /etc/init.d/atd {start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0

